# Generated by Django 4.1.10 on 2025-09-29 04:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('title', models.CharField(blank=True, default='', max_length=150, verbose_name='Свойство')),
                ('value', models.CharField(blank=True, default='', max_length=150, verbose_name='Значение')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Запись свойство/значение',
                'verbose_name_plural': 'Значения свойств товаров',
            },
        ),
    ]
