# Generated by Django 4.1.10 on 2025-09-29 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_propertyrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={'verbose_name': 'Запись свойство/значение', 'verbose_name_plural': 'Свойства товара'},
        ),
        migrations.RenameField(
            model_name='propertyrecord',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='catalog_app.good', verbose_name='Товар'),
        ),
    ]
