# Generated by Django 4.1.10 on 2025-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_goodimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Ссылка'),
        ),
    ]
