# Generated by Django 4.1.10 on 2025-10-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0007_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pic_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Имя пиктограммы'),
        ),
    ]
