# Generated by Django 4.1.10 on 2025-10-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0009_good_k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='k',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=15, null=True, verbose_name='К.'),
        ),
    ]
