# Generated by Django 4.1.10 on 2025-11-06 03:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0010_alter_good_k'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сompilation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменен')),
                ('slug', models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Ссылка')),
                ('description', models.CharField(blank=True, default='', max_length=2048, verbose_name='Описание')),
                ('preview_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.image', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Подборка',
                'verbose_name_plural': 'Подборки',
            },
        ),
        migrations.CreateModel(
            name='СompilationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('compilation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.сompilation', verbose_name='Подборка')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_app.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Элемент подборки',
                'verbose_name_plural': 'Элементы подборок',
            },
        ),
    ]
