# Generated by Django 4.1.10 on 2025-11-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0011_сompilation_сompilationitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сompilation',
            new_name='Compilation',
        ),
        migrations.RenameModel(
            old_name='СompilationItem',
            new_name='CompilationItem',
        ),
    ]
