# Generated by Django 4.1.10 on 2025-11-06 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0012_rename_сompilation_compilation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category', verbose_name='Подборка'),
        ),
    ]
