# Generated by Django 4.1.10 on 2025-11-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0013_compilation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.category', verbose_name='Категория'),
        ),
    ]
