# Generated by Django 4.1.10 on 2025-11-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0014_alter_compilation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='seo_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<description>'),
        ),
        migrations.AddField(
            model_name='good',
            name='seo_keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<keywords>'),
        ),
        migrations.AddField(
            model_name='good',
            name='seo_title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<title>'),
        ),
    ]
