# Generated by Django 4.1.10 on 2025-11-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0015_good_seo_description_good_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='compilation',
            name='sort_ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='good',
            name='sort_ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='image',
            name='sort_ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
