# Generated by Django 4.1.10 on 2025-11-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0017_offer_good_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Короткое имя'),
        ),
    ]
