# Generated by Django 4.1.10 on 2026-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0018_good_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecord',
            options={'ordering': ('sort_ordering',), 'verbose_name': 'Запись свойство/значение', 'verbose_name_plural': 'Свойства товара'},
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='sort_ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
