# Generated by Django 4.1.10 on 2026-08-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0019_alter_propertyrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='registry_link',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ссылка на сертификат/декларацию'),
        ),
    ]
