# Generated by Django 4.1.10 on 2026-08-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0020_good_registry_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='registry_link',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Ссылка на сертификат/декларацию'),
        ),
    ]
