# Generated by Django 4.1.10 on 2026-09-18 04:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0021_alter_good_registry_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_text',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='SEO-текст листинга'),
        ),
        migrations.AlterField(
            model_name='good',
            name='registry_link',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Ссылка на сертификат/декларацию (https://pub.fsa.gov.ru/)'),
        ),
    ]
