# Generated by Django 4.1.10 on 2026-09-30 07:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0023_alter_good_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
