# Generated by Django 4.1.10 on 2026-09-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0024_alter_good_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='hit',
            field=models.BooleanField(default=False, verbose_name='Хит'),
        ),
        migrations.AddField(
            model_name='good',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='good',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
    ]
