# Generated by Django 4.1.10 on 2026-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0025_good_hit_good_new_good_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Описание'),
        ),
    ]
