# Generated by Django 4.1.10 on 2026-09-30 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0026_alter_good_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedGood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='catalog_app.good', verbose_name='Товар')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_app.good', verbose_name='Сопутствующий товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
