# Generated by Django 4.1.10 on 2026-09-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0027_relatedgood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedgood',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_goods', to='catalog_app.good', verbose_name='Товар'),
        ),
    ]
