# Generated by Django 4.1.10 on 2026-09-30 08:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0028_alter_relatedgood_good'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedgood',
            options={'verbose_name': 'Сопутствующий товар', 'verbose_name_plural': 'Сопутствующие товары'},
        ),
        migrations.AddField(
            model_name='good',
            name='add_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
