# Generated by Django 4.1.10 on 2025-09-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменен'),
        ),
    ]
