# Generated by Django 4.1.10 on 2025-09-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_alter_pin_client_contract'),
        ('order_app', '0004_cartitem_created_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='client_app.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='client_app.contract', verbose_name='Клиент'),
        ),
    ]
