# Generated by Django 4.1.10 on 2025-10-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_remove_client_contract'),
        ('catalog_app', '0007_category_slug'),
        ('order_app', '0005_remove_order_client_order_contract_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('client', 'good')},
        ),
    ]
