# Generated by Django 4.1.10 on 2025-10-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_remove_client_contract'),
        ('order_app', '0006_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='client_app.client', verbose_name='Клиент'),
        ),
    ]
