# Generated by Django 4.1.10 on 2025-11-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_alter_cartitem_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorder',
            name='sort_ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
