# Generated by Django 4.1.10 on 2025-12-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_statusorder_sort_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Самовывоз'), (2, 'Транспортная компания')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Наименование (ФИО)'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Телефон'),
        ),
    ]
