# Generated by Django 4.1.10 on 2025-09-19 05:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True, verbose_name='Остаток')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog_app.good', verbose_name='Товар')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='client_app.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Запись цен',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
