# Generated by Django 5.2.6 on 2025-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceitem',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True, verbose_name='Остаток'),
        ),
    ]
