# Generated by Django 4.1.10 on 2025-09-25 03:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_category_created_at_category_updated_at_and_more'),
        ('client_app', '0005_client_contract'),
        ('price_app', '0002_priceitem_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualPriceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='client_app.client', verbose_name='Клиент')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_prices', to='catalog_app.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Запись персональных цен',
                'verbose_name_plural': 'Персональные цены',
            },
        ),
    ]
