# Generated by Django 4.1.10 on 2026-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0002_doc_sort_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='show_in_docs',
            field=models.BooleanField(default=False, verbose_name='Показывать в документах'),
        ),
        migrations.AddField(
            model_name='doc',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Ссылка'),
        ),
    ]
