# Generated by Django 4.1.10 on 2025-09-19 05:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('code', models.CharField(blank=True, default='', max_length=11, verbose_name='Код (1С:ERP)')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='client_app.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
