# Generated by Django 5.2.6 on 2025-09-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Код (1С:ERP)'),
        ),
    ]
