# Generated by Django 4.1.10 on 2025-09-19 10:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_client_created_at_client_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('exp_date', models.DateTimeField(blank=True, null=True, verbose_name='Годен до')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.client', verbose_name='Клиента')),
            ],
            options={
                'verbose_name': 'Пин-код',
                'verbose_name_plural': 'Пин-коды',
            },
        ),
    ]
