# Generated by Django 4.1.10 on 2025-09-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='exp_date',
        ),
    ]
