# Generated by Django 4.1.10 on 2025-09-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_remove_pin_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Договор'),
        ),
    ]
