# Generated by Django 4.1.10 on 2025-09-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_alter_pin_client_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contract',
        ),
    ]
