# Generated by Django 4.1.10 on 2025-11-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_organization_contract_address_contract_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sort_ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sort_ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sort_ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='region',
            name='sort_ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
