# Generated by Django 4.1.10 on 2026-04-07 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_client_sort_ordering_contract_sort_ordering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменен')),
                ('sort_ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
                ('name', models.CharField(db_index=True, default='', max_length=255, verbose_name='Наименование')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='client_app.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
            },
        ),
    ]
