# Generated by Django 4.1.10 on 2026-05-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='client_app.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Адрес доставки'),
        ),
    ]
