from django.urls import path
from api_app.views import (
    PinView,
    TokenView,
    CategoryView,
    GoodView,
    CompilationView,
    DocView,
    DataView,
    OrderView,
    ContractView,
    NewOrderView,
    UpdateOrderStatusView,
    CartView,
    CartSetView,
    CartAddView,
    CartDeleteView,
    CartClearView,
    WishView,
    WishSetView,
    WishDeleteView,
    WishClearView,
    RequestView,
    FeedbackView,
    PageView,
)

app_name = "api_app"

urlpatterns = [
    path("v1/pin/", PinView.as_view()),
    path("v1/token/", TokenView.as_view()),
    path("v1/category/", CategoryView.as_view()),
    path("v1/category/<str:slug>/", CategoryView.as_view()),
    path("v1/contracts/", ContractView.as_view()),
    path("v1/good/", GoodView.as_view()),
    path("v1/good/<str:slug>/", GoodView.as_view()),
    path("v1/compilation/", CompilationView.as_view()),
    path("v1/doc/", DocView.as_view()),
    path("v1/data/", DataView.as_view()),
    path("v1/orders/", OrderView.as_view()),
    path("v1/orders/get-new/", NewOrderView.as_view()),
    path("v1/orders/update-statuses/", UpdateOrderStatusView.as_view()),
    path("v1/cart/", CartView.as_view()),
    path("v1/cart/set/", CartSetView.as_view()),
    path("v1/cart/add/", CartAddView.as_view()),
    path("v1/cart/delete/", CartDeleteView.as_view()),
    path("v1/cart/clear/", CartClearView.as_view()),
    path("v1/wish/", WishView.as_view()),
    path("v1/wish/set/", WishSetView.as_view()),
    path("v1/wish/delete/", WishDeleteView.as_view()),
    path("v1/wish/clear/", WishClearView.as_view()),
    path("v1/request/", RequestView.as_view()),
    path("v1/feedback/", FeedbackView.as_view()),
    path("v1/page/", PageView.as_view()),
]
