# Generated by Django 4.1.10 on 2025-11-14 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменен')),
                ('url', models.CharField(default='', max_length=150, verbose_name='Наименование')),
                ('seo_title', models.TextField(blank=True, default='', null=True, verbose_name='<title>')),
                ('seo_description', models.TextField(blank=True, default='', null=True, verbose_name='<description>')),
                ('seo_keywords', models.TextField(blank=True, default='', null=True, verbose_name='<keywords>')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
