# Generated by Django 4.1.10 on 2025-11-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
    ]
