# Generated by Django 4.1.10 on 2026-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworderrecipient',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='E-mail'),
        ),
    ]
