# Generated by Django 4.1.10 on 2026-02-20 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_client_sort_ordering_contract_sort_ordering_and_more'),
        ('settings_app', '0002_alter_neworderrecipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworderrecipient',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.region', verbose_name='Регион'),
        ),
    ]
